### ISSUE TITLE
params for task doesnt work

### ISSUE THREAD

**Issue by jakubigla** [martinj/phing-task-jshint#7]
my build.xml:
<path id="phing.tasks.path">
        <pathelement dir="./support/phing/"/>
    </path>

```
<taskdef name="jshint" classname="JsHintTask">
    <classpath refid="phing.tasks.path"/>
</taskdef>
```

<target name="lint-js">
        <jshint haltonfailure="true">
            <fileset dir="${static}/src/js">
                <include name="**/*.js"/>
                <exclude name="lib/"></exclude>
            </fileset>
        </jshint>
    </target>

error:
build.xml:115:30: phing.tasks.ext.JsHintTask doesn't support the 'haltonfailure' attribute.

**Comment by martinj** [comment]
Seems like it stop working in phing 2.8.0.. still works in 2.7.0.
I don't use phing no more, so i won't look any further into this.
If you find a solution to it, you are more then welcome to supply a pull request with a fix.

**Comment by mhujer** [comment]
JSHint task is already part of official phing dist - https://github.com/phingofficial/phing/pull/237

**Comment by martinj** [comment]
@mhujer thanks for pointing that out. 
I have updated the readme of this project with deprecation note an reference to the official task.

**Comment by mhujer** [comment]
:+1:
